version: "3.7"

services:
  postgres_db:
    image: postgres
    container_name: PostgresCont
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
